from tkinter import*
win = Tk()
win.title('CheckButton Widget')
win.geometry('300x200+300+200')
cbv1,cbv2,cbv3,cbv4 = BooleanVar(),BooleanVar(),BooleanVar(),BooleanVar()
photo = PhotoImage(file = 'unnamed_reduce.png')
x = lambda : print('C++ Checked')
label = Label(win,text='Competitive Coding with ?').pack()
cb1 = Checkbutton(win,text = 'C++',activeforeground = 'Red',bg='Violet',bd = 10,command = x,variable = cbv1,onvalue = 1,offvalue = 0).pack()
cb2 = Checkbutton(win,text = 'Python3',activeforeground = 'pink',image=photo,compound = LEFT,variable = cbv2,onvalue = 1,offvalue = 0).pack()
cb3 = Checkbutton(win,text = 'Java',activeforeground = 'yellow',cursor = 'cross',variable = cbv3,onvalue = 1,offvalue = 0).pack()
cb4 = Checkbutton(win,text = 'R',activeforeground = 'brown',variable = cbv4,onvalue = 1,offvalue = 0).pack()
win.mainloop()
print(cbv1.get())
