from tkinter import*
window = Tk()
window.title('Entry Widget')
window.geometry('300x200+300+200')
entry_text = StringVar()
name = Label(window, text="Name").place(x=10, y=50)
email = Label(window, text="Email").place(x=10, y=70)
password = Label(window,text ='Password').place(x=10,y=90)
e1 = Entry(window,bg='pink',exportselection=0,selectbackground='red',textvariable = entry_text).place(x=70,y=50)
e2 = Entry(window,fg='blue',insertontime = 50,xscrollcommand=100).place(x=70,y=70)
e3 = Entry(window,cursor='heart',insertofftime = 50,show='*').place(x=70,y=90)
cb = Checkbutton(window,text='Remember Me').place(x=80,y=120)
btn = Button(window,text='Submit',command=window.destroy).place(x=110,y=150)
window.mainloop()
print(entry_text.get())