from tkinter import*
root = Tk()
root.title('ListBox Widget')
root.geometry('300x400')
label = Label(root,text = 'List of Items :').pack()
lb = Listbox(root,selectmode='extended')
lb.insert(1,'Sugar')
lb.insert(2,'Rice')
lb.insert(3,'Flour')
lb.insert(4,'Eggs')
lb.insert(5,'Chicken')
lb.insert(6,'Masala')
lb.insert(7,'Salad')
lb.insert(8,'Sugar')
lb.insert(9,'Rice')
lb.insert(10,'Flour')
lb.insert(11,'Eggs')
lb.insert(12,'Chicken')
lb.insert(13,'Masala')
lb.insert(14,'Salad')
lb.pack()
root.mainloop()