from tkinter import Tk,messagebox,Button
root = Tk()
root.title('MessageBox Widget')
root.geometry('600x400+800+80')
sinfo = lambda :messagebox.showinfo('Information','Good going till now!!')
swarm = lambda :messagebox.showwarning('Warning','Good not to stop here!')
serror = lambda :messagebox.showerror('Error','Increase your speed ')
sask = lambda :messagebox.askquestion('Question','Can you do it')
saskc = lambda :messagebox.askokcancel('Question','Can you keep it up')
saskyn = lambda :messagebox.askyesno('Question','Say yes ya no?')
saskrc = lambda :messagebox.askretrycancel('Question','This much done na?')
bt1 = Button(root,text='showinfo',command=sinfo).place(x=10,y=10)
bt2 = Button(root,text='showwarning',command=swarm).place(x=80,y=10)
bt3 = Button(root,text='showerror',command=serror).place(x=160,y=10)
bt4 = Button(root,text='askquestion',command=sask).place(x=240,y=10)
bt5 = Button(root,text='askokcancel',command=saskc).place(x=10,y=50)
bt6 = Button(root,text='askyesno',command=saskyn).place(x=80,y=50)
bt7 = Button(root,text='askretrycancel',command=saskrc).place(x=160,y=50)
root.mainloop()